package com.imooc.grocers.dal;

import com.imooc.grocers.model.ShopModel;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

public interface ShopModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sat Oct 26 14:00:26 EDT 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sat Oct 26 14:00:26 EDT 2019
     */
    int insert(ShopModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sat Oct 26 14:00:26 EDT 2019
     */
    int insertSelective(ShopModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sat Oct 26 14:00:26 EDT 2019
     */
    ShopModel selectByPrimaryKey(Integer id);

    List<ShopModel> selectAll();

    Integer countAllShop();

    List<ShopModel> recommend(@Param(value = "latitude") BigDecimal latitude,
                              @Param(value = "longitude") BigDecimal longitude);

    List<ShopModel> search(@Param(value = "latitude") BigDecimal latitude,
                           @Param(value = "longitude") BigDecimal longitude,
                           @Param(value = "keyword") String keyword,
                           @Param(value = "orderby") Integer orderby,
                           @Param(value = "categoryId") Integer categoryId,
                           @Param(value = "tags") String tags);

    List<Map<String, Object>> searchGroupByTags(@Param("keyword") String keyword,
                                                @Param("categoryId") Integer categoryId,
                                                @Param("tags") String tags);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sat Oct 26 14:00:26 EDT 2019
     */
    int updateByPrimaryKeySelective(ShopModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sat Oct 26 14:00:26 EDT 2019
     */
    int updateByPrimaryKey(ShopModel record);
}