package com.imooc.grocers.dal;

import com.imooc.grocers.model.UserModel;
import org.apache.ibatis.annotations.Param;

public interface UserModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Oct 14 17:09:57 EDT 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Oct 14 17:09:57 EDT 2019
     */
    int insert(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Oct 14 17:09:57 EDT 2019
     */
    int insertSelective(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Oct 14 17:09:57 EDT 2019
     */
    UserModel selectByPrimaryKey(Integer id);

    UserModel selectByTelephoneAndPassword(@Param("telephone") String telephone, @Param("password") String password);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Oct 14 17:09:57 EDT 2019
     */
    int updateByPrimaryKeySelective(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Oct 14 17:09:57 EDT 2019
     */
    int updateByPrimaryKey(UserModel record);

    Integer countAllUser();
}